name: Symfony Tests Workflow

on:
    push:
        branches:
            master
    pull_request:
permissions:
    contents: read
    issues: write
    pull-requests: write
jobs:
    symfony-tests:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
                    MYSQL_ROOT_PASSWORD:
                    MYSQL_DATABASE: symfotest
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping --silent"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2.4'
                  extensions: mbstring, pdo_mysql
                  ini-values: post_max_size=256M, upload_max_filesize=256M
                  coverage: none
            # Configure the project (dev -> test)
            - name: Configure environment
              run: |
                if [ -f .env.test ]; then
                    cp .env.test .env
                else
                    echo "APP_ENV=test" > .env
                fi

            - name: Install Composer
              run: composer install --no-progress --no-suggest

            - name: Create Database
              run: php bin/console doctrine:database:create --if-not-exists --no-interaction

            - name: Run migrations
              run: php bin/console d:m:m --no-interaction

            - name: Start PHP server
              run: php -S 127.0.0.1:8000 -t public &
              env:
                  APP_ENV: test

            - name: Cypress run
              uses: cypress-io/github-action@v6